### ISSUE TITLE
Would you consider exposing this functionality as a library?

### ISSUE THREAD

**Issue by Enrico2** [rinchsan/gosimports#90]
I'm writing a Go code generator, and I'd love to be able to apply gosimports after generation, before writing the actual file, so I'm holding a `[]byte` -- for some reason using `imports.Process` takes a loooooooong time.

**Comment by rinchsan** [comment]
@Enrico2 
Thank you for submitting a feature request issue!

I am going to consider exporting `internal/imports.Process` as `gosimports.Process` for example.

Any other detailed requests for exposing gosimports functionality?

**Comment by Enrico2** [comment]
Hm, nothing special: I'd like to be able to invoke its functionality (including possible flags / configs) from code, and apply it to either a `string` or `[]byte` (I'd use the latter)

**Comment by rinchsan** [comment]
@Enrico2 
Now `gosimports.Process` has been exported! https://github.com/rinchsan/gosimports/releases/tag/v0.3.0
Please try it out, and welcome to your further feedbacks.

Anyway, closing this one for now.
